# Generated by Django 4.2.13 on 2024-07-17 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='useremail',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
